on:
  workflow_dispatch:

name: test_WF

jobs:
  write-message:
    runs-on: ubuntu-latest
    steps:
      - uses: r-lib/actions/setup-r@v2
      - name: print-message
        run: Rscript -e 'print("a test workflow")'
